const char *controller_html =
"<html>\n"
"<head>\n"
"<title>RGB Controller</title>\n"
"<meta name='viewport' content='width=device-width, initial-scale=1'>\n"
"<style>\n"
"body {\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div style='padding: 10%; display:grid; width:80%; align-items: stretch; row-gap: 20px; grid-template-columns: 100%;'>\n"
"<input type='range' min='0' max='1023' id='rSlider' value='0'>\n"
"<input type='range' min='0' max='1023' id='gSlider' value='0'>\n"
"<input type='range' min='0' max='1023' id='bSlider' value='0'>\n"
"</div>\n"
"\n"
"<script>\n"
"var rVal = 0;\n"
"var gVal = 0;\n"
"var bVal = 0;\n"
"\n"
"const rSlider = document.getElementById('rSlider');\n"
"const gSlider = document.getElementById('gSlider');\n"
"const bSlider = document.getElementById('bSlider');\n"
"\n"
"rSlider.onchange = updateSliderRGB;\n"
"gSlider.onchange = updateSliderRGB;\n"
"bSlider.onchange = updateSliderRGB;\n"
"\n"
"function updateSliderRGB() {\n"
"rVal = rSlider.value;\n"
"gVal = gSlider.value;\n"
"bVal = bSlider.value;\n"
"updateRGB();\n"
"}\n"
"\n"
"function updateRGB() {\n"
"fetch('/RGB=' + rVal + ',' + gVal + ',' + bVal);\n"
"}\n"
"</script>\n"
"</body>\n"
"</html>\n";
