const char *manifest_html =
"{\n"
"\"manifest_version\": 2,\n"
"\"version\": \"1\",\n"
"\"short_name\": \"RGBC\",\n"
"\"name\": \"RGB Controller\",\n"
"\"icons\": [\n"
"{\n"
"\"src\": \"icon.png\",\n"
"\"sizes\": \"192x192\",\n"
"\"type\": \"image/png\"\n"
"}\n"
"],\n"
"\"start_url\": \"/\",\n"
"\"display\": \"standalone\",\n"
"\"orientation\": \"portrait\"\n"
"}\n"
"\n";
